import type { Initiative } from './types';

// All 30 seed initiatives get proposedScore = agreedScore = valueScore (pre-process history).
// sponsor renamed to sponsorName; returnedToRequester removed.
export const SEED_INITIATIVES: Initiative[] = [
  // ── In delivery (10) ──────────────────────────────────────────────────────
  {
    id: 'i001',
    fundingType: 'CAPEX',
    name: 'AVM Operating Model Redesign',
    objective: 'Redesign the AVM workflow to cut average panel turnaround by 30% and improve first-instruction utilisation.',
    driver: 'Strategic programme',
    businessArea: 'Field Ops',
    stage: 'In delivery',
    rag: 'Amber',
    priority: 'High',
    valueScore: 11,
    proposedScore: 11,
    agreedScore: 11,
    sponsorName: 'Claire Donovan',
    businessOwner: 'Marcus Webb',
    projectManager: 'Priya Nair',
    demand: { ba: 8, dev: 12, pm: 5, ops: 3 },
    systemsTouched: ['VAMS', 'Panel Hub', 'AVM Engine'],
    fundingStatus: 'Approved',
    budget: 480,
    startDate: '2026-03-01',
    endDate: '2026-12-31',
    nextMilestone: 'UAT sign-off',
    nextMilestoneDate: '2026-09-30',
    spofNote: 'Single AVM architect; no internal cover if unavailable.',
    lenderVisible: false,
    accelerated: false,
  },
  {
    id: 'i002',
    fundingType: 'CAPEX',
    name: 'Barclays Direct Integration',
    objective: 'Deliver a direct API channel for Barclays instruction and status reporting, replacing the intermediary portal.',
    driver: 'Lender mandated or client request',
    businessArea: 'Technical',
    stage: 'In delivery',
    rag: 'Green',
    priority: 'Critical',
    valueScore: 12,
    proposedScore: 12,
    agreedScore: 12,
    sponsorName: 'James Hartley',
    businessOwner: 'Sarah Griffiths',
    projectManager: 'Ben Caldwell',
    demand: { ba: 5, dev: 18, pm: 4, ops: 2 },
    systemsTouched: ['Lender API', 'VAMS', 'Reporting Hub'],
    fundingStatus: 'Approved',
    budget: 320,
    startDate: '2026-01-15',
    endDate: '2026-10-31',
    nextMilestone: 'Barclays UAT entry',
    nextMilestoneDate: '2026-09-15',
    lenderVisible: true,
    accelerated: false,
  },
  {
    id: 'i003',
    fundingType: 'CAPEX',
    name: 'CRM Dynamics 365 Migration',
    objective: 'Replace the legacy CRM with Microsoft Dynamics 365 to consolidate client and lender relationship data.',
    driver: 'Technology or infrastructure',
    businessArea: 'Customer Care',
    stage: 'In delivery',
    rag: 'Red',
    priority: 'High',
    valueScore: 9,
    proposedScore: 9,
    agreedScore: 9,
    sponsorName: 'Rachel Burns',
    businessOwner: 'David Ruck',
    projectManager: 'Fiona Marsh',
    demand: { ba: 10, dev: 20, pm: 6, ops: 4 },
    systemsTouched: ['CRM Dynamics 365', 'Lender API', 'Finance System'],
    fundingStatus: 'Approved',
    budget: 750,
    startDate: '2025-10-01',
    endDate: '2026-12-31',
    nextMilestone: 'Data migration dry-run',
    nextMilestoneDate: '2026-09-20',
    spofNote: 'External SI lead is sole Dynamics 365 architect; contract renewal under review.',
    lenderVisible: false,
    accelerated: false,
  },
  {
    id: 'i004',
    fundingType: 'CAPEX',
    name: 'e.survIQ Triage Module',
    objective: 'Build the automated triage layer of e.survIQ to route instructions to the optimal assessment channel.',
    driver: 'Strategic programme',
    businessArea: 'IQ',
    stage: 'In delivery',
    rag: 'Green',
    priority: 'High',
    valueScore: 10,
    proposedScore: 10,
    agreedScore: 10,
    sponsorName: 'Claire Donovan',
    businessOwner: 'Marcus Webb',
    projectManager: 'Priya Nair',
    demand: { ba: 6, dev: 15, pm: 4, ops: 2 },
    systemsTouched: ['e.survIQ', 'VAMS', 'AVM Engine'],
    fundingStatus: 'Approved',
    budget: 560,
    startDate: '2026-02-01',
    endDate: '2026-11-30',
    nextMilestone: 'Beta release to pilot panel',
    nextMilestoneDate: '2026-10-15',
    lenderVisible: false,
    accelerated: false,
  },
  {
    id: 'i005',
    fundingType: 'CAPEX',
    name: 'e.survIQ Data Lake',
    objective: 'Establish a centralised property data lake to support e.survIQ model training and analytics.',
    driver: 'Strategic programme',
    businessArea: 'IQ',
    stage: 'In delivery',
    rag: 'Amber',
    priority: 'High',
    valueScore: 11,
    proposedScore: 11,
    agreedScore: 11,
    sponsorName: 'Claire Donovan',
    businessOwner: 'Paul Jenkins',
    projectManager: 'Ben Caldwell',
    demand: { ba: 4, dev: 22, pm: 3, ops: 5 },
    systemsTouched: ['Data Lake', 'e.survIQ', 'Reporting Hub'],
    fundingStatus: 'Approved',
    budget: 620,
    startDate: '2026-01-01',
    endDate: '2027-03-31',
    nextMilestone: 'Phase 1 ingestion complete',
    nextMilestoneDate: '2026-10-01',
    lenderVisible: false,
    accelerated: false,
  },
  {
    id: 'i009',
    fundingType: 'CAPEX',
    name: 'Scottish Single Survey Migration',
    objective: 'Migrate Scottish Single Survey instructions to the new digital workflow ahead of the regulatory deadline.',
    driver: 'Regulatory or compliance',
    businessArea: 'Risk',
    stage: 'In delivery',
    rag: 'Red',
    priority: 'Critical',
    valueScore: 13,
    proposedScore: 13,
    agreedScore: 13,
    sponsorName: 'Sandra Chen',
    businessOwner: 'Helen Moore',
    projectManager: 'Yasmin Ali',
    demand: { ba: 7, dev: 10, pm: 5, ops: 6 },
    systemsTouched: ['VAMS', 'Surveyor Portal', 'Document Management'],
    fundingStatus: 'Approved',
    budget: 290,
    startDate: '2026-04-01',
    endDate: '2026-11-30',
    nextMilestone: 'Regulator sign-off submission',
    nextMilestoneDate: '2026-09-30',
    spofNote: 'Single Scottish compliance specialist; no cover available.',
    lenderVisible: true,
    accelerated: false,
  },
  {
    id: 'i010',
    fundingType: 'CAPEX',
    name: 'Panel Hub Capacity Uplift',
    objective: 'Increase Panel Hub throughput to support the 15% volume growth forecast for Q1 2027.',
    driver: 'Operational improvement',
    businessArea: 'Field Ops',
    stage: 'In delivery',
    rag: 'Green',
    priority: 'Medium',
    valueScore: 7,
    proposedScore: 7,
    agreedScore: 7,
    sponsorName: 'Tom Whitfield',
    businessOwner: 'Richard Fox',
    projectManager: 'Nick Turner',
    demand: { ba: 3, dev: 8, pm: 3, ops: 4 },
    systemsTouched: ['Panel Hub', 'VAMS'],
    fundingStatus: 'Approved',
    budget: 180,
    startDate: '2026-06-01',
    endDate: '2026-12-31',
    nextMilestone: 'Performance testing',
    nextMilestoneDate: '2026-10-31',
    lenderVisible: false,
    accelerated: false,
  },
  {
    id: 'i011',
    fundingType: 'OPEX',
    name: 'Data Retention & GDPR Remediation',
    objective: 'Implement automated data retention schedules and remediate legacy GDPR compliance gaps across key systems.',
    driver: 'Regulatory or compliance',
    businessArea: 'Risk',
    stage: 'In delivery',
    rag: 'Amber',
    priority: 'High',
    valueScore: 12,
    proposedScore: 12,
    agreedScore: 12,
    sponsorName: 'Sandra Chen',
    businessOwner: 'Helen Moore',
    projectManager: 'Emma Scott',
    demand: { ba: 5, dev: 8, pm: 4, ops: 3 },
    systemsTouched: ['VAMS', 'CRM Dynamics 365', 'Document Management', 'Compliance Register'],
    fundingStatus: 'Approved',
    budget: 210,
    startDate: '2026-05-01',
    endDate: '2026-12-31',
    nextMilestone: 'DPA audit remediation complete',
    nextMilestoneDate: '2026-10-15',
    lenderVisible: false,
    accelerated: false,
  },
  {
    id: 'i012',
    fundingType: 'CAPEX',
    name: 'NatWest API Refresh',
    objective: 'Upgrade the NatWest lender integration to v3 API ahead of their platform decommission date.',
    driver: 'Lender mandated or client request',
    businessArea: 'Technical',
    stage: 'In delivery',
    rag: 'Green',
    priority: 'High',
    valueScore: 10,
    proposedScore: 10,
    agreedScore: 10,
    sponsorName: 'James Hartley',
    businessOwner: 'Sarah Griffiths',
    projectManager: 'Chris Powell',
    demand: { ba: 3, dev: 10, pm: 3, ops: 1 },
    systemsTouched: ['Lender API', 'VAMS'],
    fundingStatus: 'Approved',
    budget: 150,
    startDate: '2026-06-01',
    endDate: '2026-10-31',
    nextMilestone: 'NatWest integration testing',
    nextMilestoneDate: '2026-09-20',
    lenderVisible: true,
    accelerated: false,
  },
  {
    id: 'i017',
    fundingType: 'OPEX',
    name: 'Supplier Risk Management',
    objective: 'Introduce a formal supplier risk register and monitoring process for tier-1 panel members.',
    driver: 'Regulatory or compliance',
    businessArea: 'Risk',
    stage: 'In delivery',
    rag: 'Green',
    priority: 'Medium',
    valueScore: 8,
    proposedScore: 8,
    agreedScore: 8,
    sponsorName: 'Rachel Burns',
    businessOwner: 'Richard Fox',
    projectManager: 'Fiona Marsh',
    demand: { ba: 4, dev: 5, pm: 3, ops: 2 },
    systemsTouched: ['Compliance Register', 'Panel Hub'],
    fundingStatus: 'Approved',
    budget: 95,
    startDate: '2026-07-01',
    endDate: '2026-12-31',
    nextMilestone: 'Risk register live',
    nextMilestoneDate: '2026-10-01',
    lenderVisible: false,
    accelerated: false,
  },
  // ── Under assessment (5) ──────────────────────────────────────────────────
  {
    id: 'i007',
    fundingType: 'CAPEX',
    name: 'e.survIQ Portal',
    objective: 'Build a lender-facing portal for e.survIQ results, commentary, and report access.',
    driver: 'Strategic programme',
    businessArea: 'IQ',
    stage: 'Under assessment',
    rag: 'Green',
    priority: 'High',
    valueScore: 10,
    proposedScore: 10,
    agreedScore: 10,
    sponsorName: 'Claire Donovan',
    businessOwner: 'Marcus Webb',
    projectManager: 'Priya Nair',
    demand: { ba: 6, dev: 18, pm: 4, ops: 2 },
    systemsTouched: ['e.survIQ', 'Lender API', 'Surveyor Portal'],
    fundingStatus: 'Pending approval',
    budget: 430,
    startDate: '2027-01-01',
    endDate: '2027-09-30',
    nextMilestone: 'Business case approved',
    nextMilestoneDate: '2026-10-31',
    lenderVisible: true,
    accelerated: false,
  },
  {
    id: 'i013',
    fundingType: 'CAPEX',
    name: 'Valuation Report Digitisation',
    objective: 'Replace paper and PDF valuation reports with a structured digital output consumable by lender systems.',
    driver: 'Operational improvement',
    businessArea: 'Field Ops',
    stage: 'Under assessment',
    rag: 'Amber',
    priority: 'Medium',
    valueScore: 6,
    proposedScore: 6,
    agreedScore: 6,
    sponsorName: 'Tom Whitfield',
    businessOwner: 'David Ruck',
    projectManager: 'Nick Turner',
    demand: { ba: 8, dev: 14, pm: 4, ops: 3 },
    systemsTouched: ['VAMS', 'Document Management', 'Lender API'],
    fundingStatus: 'Pending approval',
    budget: 380,
    startDate: '2027-02-01',
    endDate: '2027-12-31',
    nextMilestone: 'Feasibility study complete',
    nextMilestoneDate: '2026-11-30',
    lenderVisible: false,
    accelerated: false,
  },
  {
    id: 'i014',
    fundingType: 'CAPEX',
    name: 'Surveyor Mobile App v2',
    objective: 'Rebuild the surveyor field app with offline capability and integrated photo and measurement tools.',
    driver: 'Technology or infrastructure',
    businessArea: 'Field Ops',
    stage: 'Under assessment',
    rag: 'Green',
    priority: 'Medium',
    valueScore: 8,
    proposedScore: 8,
    agreedScore: 8,
    sponsorName: 'Lisa Patel',
    businessOwner: 'Richard Fox',
    projectManager: 'Emma Scott',
    demand: { ba: 5, dev: 20, pm: 4, ops: 2 },
    systemsTouched: ['Surveyor Portal', 'VAMS', 'Document Management'],
    fundingStatus: 'Pending approval',
    budget: 510,
    startDate: '2027-01-01',
    endDate: '2027-12-31',
    nextMilestone: 'Prototype sign-off',
    nextMilestoneDate: '2026-12-15',
    lenderVisible: false,
    accelerated: false,
  },
  {
    id: 'i015',
    fundingType: 'CAPEX',
    name: 'Legacy VAMS Decommission',
    objective: 'Retire the legacy VAMS instance once all dependent workflows have migrated to the new platform.',
    driver: 'Technology or infrastructure',
    businessArea: 'Technical',
    stage: 'Under assessment',
    rag: 'Green',
    priority: 'Medium',
    valueScore: 7,
    proposedScore: 7,
    agreedScore: 7,
    sponsorName: 'Rachel Burns',
    businessOwner: 'Paul Jenkins',
    projectManager: 'Chris Powell',
    demand: { ba: 4, dev: 12, pm: 3, ops: 5 },
    systemsTouched: ['VAMS', 'AVM Engine', 'Panel Hub'],
    fundingStatus: 'Pending approval',
    budget: 140,
    startDate: '2027-04-01',
    endDate: '2027-12-31',
    nextMilestone: 'Dependency mapping complete',
    nextMilestoneDate: '2026-11-01',
    lenderVisible: false,
    accelerated: false,
  },
  {
    id: 'i026',
    fundingType: 'OPEX',
    name: 'Data Science Centre of Excellence',
    objective: 'Establish a dedicated data science capability to accelerate model development for e.survIQ and AVM.',
    driver: 'Strategic programme',
    businessArea: 'IQ',
    stage: 'Under assessment',
    rag: 'Amber',
    priority: 'Medium',
    valueScore: 9,
    proposedScore: 9,
    agreedScore: 9,
    sponsorName: 'Claire Donovan',
    businessOwner: 'Paul Jenkins',
    projectManager: 'Priya Nair',
    demand: { ba: 3, dev: 5, pm: 3, ops: 1 },
    systemsTouched: ['Data Lake', 'e.survIQ', 'Reporting Hub'],
    fundingStatus: 'Pending approval',
    budget: 200,
    startDate: '2027-01-01',
    endDate: '2027-12-31',
    nextMilestone: 'Headcount plan approved',
    nextMilestoneDate: '2026-10-31',
    lenderVisible: false,
    accelerated: false,
  },
  // ── Approved, not started (4) ─────────────────────────────────────────────
  {
    id: 'i006',
    fundingType: 'CAPEX',
    name: 'e.survIQ Decision Engine',
    objective: 'Build the core ML decision engine that automates valuation confidence scoring for AVM outputs.',
    driver: 'Strategic programme',
    businessArea: 'IQ',
    stage: 'Approved, not started',
    rag: 'Green',
    priority: 'Critical',
    valueScore: 13,
    proposedScore: 13,
    agreedScore: 13,
    sponsorName: 'Claire Donovan',
    businessOwner: 'Marcus Webb',
    projectManager: 'Ben Caldwell',
    demand: { ba: 5, dev: 25, pm: 5, ops: 3 },
    systemsTouched: ['e.survIQ', 'AVM Engine', 'Data Lake'],
    fundingStatus: 'Approved',
    budget: 890,
    startDate: '2026-11-01',
    endDate: '2027-10-31',
    nextMilestone: 'Kick-off',
    nextMilestoneDate: '2026-11-01',
    lenderVisible: false,
    accelerated: false,
  },
  {
    id: 'i016',
    fundingType: 'CAPEX',
    name: 'HSBC Lender Portal Integration',
    objective: "Integrate with HSBC's new supplier portal to automate instruction receipt and status updates.",
    driver: 'Lender mandated or client request',
    businessArea: 'Technical',
    stage: 'Approved, not started',
    rag: 'Amber',
    priority: 'High',
    valueScore: 11,
    proposedScore: 11,
    agreedScore: 11,
    sponsorName: 'James Hartley',
    businessOwner: 'Sarah Griffiths',
    projectManager: 'Chris Powell',
    demand: { ba: 4, dev: 12, pm: 4, ops: 2 },
    systemsTouched: ['Lender API', 'VAMS'],
    fundingStatus: 'Approved',
    budget: 210,
    startDate: '2026-10-01',
    endDate: '2027-04-30',
    nextMilestone: 'Kick-off',
    nextMilestoneDate: '2026-10-01',
    lenderVisible: true,
    accelerated: false,
  },
  {
    id: 'i018',
    fundingType: 'OPEX',
    name: 'Cost Centre Restructure',
    objective: 'Realign finance cost centres to reflect the new operating model and enable cleaner P&L reporting.',
    driver: 'Cost reduction',
    businessArea: 'Finance',
    stage: 'Approved, not started',
    rag: 'Green',
    priority: 'Low',
    valueScore: 5,
    proposedScore: 5,
    agreedScore: 5,
    sponsorName: 'Michael Okonkwo',
    businessOwner: 'Michael Okonkwo',
    projectManager: 'Emma Scott',
    demand: { ba: 5, dev: 3, pm: 3, ops: 2 },
    systemsTouched: ['Finance System'],
    fundingStatus: 'Approved',
    budget: 60,
    startDate: '2026-10-01',
    endDate: '2027-03-31',
    nextMilestone: 'Kick-off',
    nextMilestoneDate: '2026-10-01',
    lenderVisible: false,
    accelerated: false,
  },
  {
    id: 'i019',
    fundingType: 'CAPEX',
    name: 'Quality Assurance Automation',
    objective: 'Automate post-instruction QA checks to reduce manual review time by 40% and improve accuracy.',
    driver: 'Operational improvement',
    businessArea: 'Quality',
    stage: 'Approved, not started',
    rag: 'Green',
    priority: 'Medium',
    valueScore: 7,
    proposedScore: 7,
    agreedScore: 7,
    sponsorName: 'Lisa Patel',
    businessOwner: 'Helen Moore',
    projectManager: 'Yasmin Ali',
    demand: { ba: 6, dev: 10, pm: 3, ops: 2 },
    systemsTouched: ['Quality Platform', 'VAMS', 'Surveyor Portal'],
    fundingStatus: 'Approved',
    budget: 175,
    startDate: '2026-11-01',
    endDate: '2027-06-30',
    nextMilestone: 'Kick-off',
    nextMilestoneDate: '2026-11-01',
    lenderVisible: false,
    accelerated: false,
  },
  // ── Idea or request (4) — already through POB, awaiting PMO triage ─────────
  {
    id: 'i030',
    fundingType: 'CAPEX',
    name: 'e.survIQ Assisted AVM',
    objective: 'Develop an assisted AVM product combining model output with remote surveyor oversight for borderline cases.',
    driver: 'Strategic programme',
    businessArea: 'IQ',
    stage: 'Idea or request',
    rag: 'Green',
    priority: 'High',
    valueScore: 9,
    proposedScore: 9,
    agreedScore: 9,
    sponsorName: 'Claire Donovan',
    businessOwner: 'Marcus Webb',
    projectManager: '',
    demand: { ba: 5, dev: 20, pm: 4, ops: 3 },
    systemsTouched: ['e.survIQ', 'AVM Engine', 'Surveyor Portal'],
    fundingStatus: 'Not yet submitted',
    budget: 0,
    startDate: '',
    endDate: '',
    nextMilestone: 'Concept paper',
    nextMilestoneDate: '',
    lenderVisible: false,
    capacityConfirmed: false,
    accelerated: false,
  },
  {
    id: 'i027',
    fundingType: 'CAPEX',
    name: 'Property Data Enrichment',
    objective: 'Enrich instruction data with third-party property attributes to improve AVM model accuracy.',
    driver: 'Strategic programme',
    businessArea: 'Props',
    stage: 'Idea or request',
    rag: 'Green',
    priority: 'Medium',
    valueScore: 7,
    proposedScore: 7,
    agreedScore: 7,
    sponsorName: 'Claire Donovan',
    businessOwner: 'Paul Jenkins',
    projectManager: '',
    demand: { ba: 4, dev: 8, pm: 2, ops: 1 },
    systemsTouched: ['Data Lake', 'AVM Engine'],
    fundingStatus: 'Not yet submitted',
    budget: 0,
    startDate: '',
    endDate: '',
    nextMilestone: 'Feasibility scoping',
    nextMilestoneDate: '',
    lenderVisible: false,
    capacityConfirmed: false,
    accelerated: false,
  },
  {
    id: 'i028',
    fundingType: 'CAPEX',
    name: 'Surveyor Recruitment Portal',
    objective: 'Build a self-service portal for surveyor recruitment, credentialing, and onboarding to reduce HR overhead.',
    driver: 'Operational improvement',
    businessArea: 'Central Ops',
    stage: 'Idea or request',
    rag: 'Green',
    priority: 'Low',
    valueScore: 6,
    proposedScore: 6,
    agreedScore: 6,
    sponsorName: 'Lisa Patel',
    businessOwner: 'Richard Fox',
    projectManager: '',
    demand: { ba: 5, dev: 10, pm: 3, ops: 2 },
    systemsTouched: ['HR System', 'Surveyor Portal'],
    fundingStatus: 'Not yet submitted',
    budget: 0,
    startDate: '',
    endDate: '',
    nextMilestone: 'Initial scoping',
    nextMilestoneDate: '',
    lenderVisible: false,
    capacityConfirmed: false,
    accelerated: false,
  },
  {
    id: 'i029',
    fundingType: 'OPEX',
    name: 'Panel Rationalisation Programme',
    objective: 'Reduce the active panel size by 20% to lower management overhead and concentrate volume on high-performing surveyors.',
    driver: 'Cost reduction',
    businessArea: 'Field Ops',
    stage: 'Idea or request',
    rag: 'Green',
    priority: 'Medium',
    valueScore: 7,
    proposedScore: 7,
    agreedScore: 7,
    sponsorName: 'Tom Whitfield',
    businessOwner: 'Richard Fox',
    projectManager: '',
    demand: { ba: 3, dev: 2, pm: 2, ops: 4 },
    systemsTouched: ['Panel Hub', 'VAMS'],
    fundingStatus: 'Not yet submitted',
    budget: 0,
    startDate: '',
    endDate: '',
    nextMilestone: 'Business case draft',
    nextMilestoneDate: '',
    lenderVisible: false,
    capacityConfirmed: false,
    accelerated: false,
  },
  // ── On hold (3) ───────────────────────────────────────────────────────────
  {
    id: 'i020',
    fundingType: 'CAPEX',
    name: 'Halifax Capacity SLA Programme',
    objective: 'Implement a capacity-aware SLA management system for Halifax instructions to meet agreed response windows.',
    driver: 'Lender mandated or client request',
    businessArea: 'Central Ops',
    stage: 'On hold',
    rag: 'Amber',
    priority: 'High',
    valueScore: 10,
    proposedScore: 10,
    agreedScore: 10,
    sponsorName: 'James Hartley',
    businessOwner: 'Sarah Griffiths',
    projectManager: 'Ben Caldwell',
    demand: { ba: 5, dev: 12, pm: 4, ops: 3 },
    systemsTouched: ['VAMS', 'Panel Hub', 'Reporting Hub'],
    fundingStatus: 'Approved',
    budget: 265,
    startDate: '2026-09-01',
    endDate: '2027-03-31',
    nextMilestone: 'Stakeholder re-engagement',
    nextMilestoneDate: '2026-11-01',
    lenderVisible: true,
    accelerated: false,
  },
  {
    id: 'i021',
    fundingType: 'CAPEX',
    name: 'Finance System Upgrade',
    objective: 'Upgrade the core finance platform to the current vendor version to maintain support and access new features.',
    driver: 'Technology or infrastructure',
    businessArea: 'Finance',
    stage: 'On hold',
    rag: 'Green',
    priority: 'Medium',
    valueScore: 6,
    proposedScore: 6,
    agreedScore: 6,
    sponsorName: 'Michael Okonkwo',
    businessOwner: 'Michael Okonkwo',
    projectManager: 'Emma Scott',
    demand: { ba: 3, dev: 8, pm: 3, ops: 4 },
    systemsTouched: ['Finance System'],
    fundingStatus: 'Approved',
    budget: 310,
    startDate: '2027-01-01',
    endDate: '2027-06-30',
    nextMilestone: 'Vendor re-scoping',
    nextMilestoneDate: '2026-12-01',
    lenderVisible: false,
    accelerated: false,
  },
  {
    id: 'i022',
    fundingType: 'OPEX',
    name: 'Client Satisfaction Tracking',
    objective: 'Implement automated post-instruction client satisfaction surveys with real-time reporting.',
    driver: 'Operational improvement',
    businessArea: 'Customer Care',
    stage: 'On hold',
    rag: 'Amber',
    priority: 'Low',
    valueScore: 4,
    proposedScore: 4,
    agreedScore: 4,
    sponsorName: 'Lisa Patel',
    businessOwner: 'Helen Moore',
    projectManager: 'Nick Turner',
    demand: { ba: 3, dev: 6, pm: 2, ops: 1 },
    systemsTouched: ['CRM Dynamics 365', 'Reporting Hub'],
    fundingStatus: 'Pending approval',
    budget: 80,
    startDate: '2026-12-01',
    endDate: '2027-06-30',
    nextMilestone: 'Funding decision',
    nextMilestoneDate: '2026-11-15',
    lenderVisible: false,
    accelerated: false,
  },
  // ── Transitioning to BAU (3) ──────────────────────────────────────────────
  {
    id: 'i023',
    fundingType: 'OPEX',
    name: 'PI Insurance Renewal Process',
    objective: 'Digitise and streamline the PI insurance renewal process to reduce administrative overhead and submission errors.',
    driver: 'Regulatory or compliance',
    businessArea: 'Risk',
    stage: 'Transitioning to BAU',
    rag: 'Green',
    priority: 'Low',
    valueScore: 5,
    proposedScore: 5,
    agreedScore: 5,
    sponsorName: 'Sandra Chen',
    businessOwner: 'Helen Moore',
    projectManager: 'Yasmin Ali',
    demand: { ba: 1, dev: 1, pm: 1, ops: 1 },
    systemsTouched: ['Compliance Register', 'Document Management'],
    fundingStatus: 'Approved',
    budget: 45,
    startDate: '2026-04-01',
    endDate: '2026-09-30',
    nextMilestone: 'Handover to operations',
    nextMilestoneDate: '2026-09-30',
    lenderVisible: false,
    accelerated: false,
  },
  {
    id: 'i024',
    fundingType: 'CAPEX',
    name: 'Santander Onboarding Refresh',
    objective: 'Refresh the Santander panel onboarding workflow to align with their new supplier governance requirements.',
    driver: 'Lender mandated or client request',
    businessArea: 'New Build',
    stage: 'Transitioning to BAU',
    rag: 'Green',
    priority: 'Medium',
    valueScore: 8,
    proposedScore: 8,
    agreedScore: 8,
    sponsorName: 'James Hartley',
    businessOwner: 'Sarah Griffiths',
    projectManager: 'Chris Powell',
    demand: { ba: 1, dev: 2, pm: 1, ops: 1 },
    systemsTouched: ['Lender API', 'Panel Hub'],
    fundingStatus: 'Approved',
    budget: 70,
    startDate: '2026-05-01',
    endDate: '2026-09-30',
    nextMilestone: 'Handover to operations',
    nextMilestoneDate: '2026-09-30',
    lenderVisible: true,
    accelerated: false,
  },
  {
    id: 'i025',
    fundingType: 'OPEX',
    name: 'Compliance Training Platform',
    objective: 'Launch a mandatory compliance and CPD training platform for all panel surveyors.',
    driver: 'Regulatory or compliance',
    businessArea: 'Quality',
    stage: 'Transitioning to BAU',
    rag: 'Green',
    priority: 'Low',
    valueScore: 4,
    proposedScore: 4,
    agreedScore: 4,
    sponsorName: 'Sandra Chen',
    businessOwner: 'Helen Moore',
    projectManager: 'Emma Scott',
    demand: { ba: 1, dev: 2, pm: 1, ops: 2 },
    systemsTouched: ['HR System', 'Compliance Register'],
    fundingStatus: 'Approved',
    budget: 90,
    startDate: '2026-03-01',
    endDate: '2026-09-30',
    nextMilestone: 'Handover to L&D team',
    nextMilestoneDate: '2026-09-30',
    lenderVisible: false,
    accelerated: false,
  },
  // ── Closed (1) ────────────────────────────────────────────────────────────
  {
    id: 'i008',
    fundingType: 'OPEX',
    name: 'Legacy Invoice Processing Cleanup',
    objective: 'Resolve outstanding legacy invoice processing errors and archive redundant billing records.',
    driver: 'Other',
    businessArea: 'Finance',
    stage: 'Closed',
    rag: 'Green',
    priority: 'Low',
    valueScore: 3,
    proposedScore: 3,
    agreedScore: 3,
    sponsorName: 'Michael Okonkwo',
    businessOwner: 'Michael Okonkwo',
    projectManager: 'Emma Scott',
    demand: { ba: 0, dev: 0, pm: 0, ops: 0 },
    systemsTouched: ['Finance System'],
    fundingStatus: 'Approved',
    budget: 25,
    startDate: '2026-01-01',
    endDate: '2026-06-30',
    nextMilestone: 'Closed',
    nextMilestoneDate: '2026-06-30',
    lenderVisible: false,
    accelerated: false,
  },
];
